# Generated by Django 3.1.4 on 2021-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimage',
            old_name='image',
            new_name='url',
        ),
    ]
